version: '3.9'
services:

  ollama:
    image: ollama/ollama:latest
    restart: always
    container_name: ollama
    ports:
      - 11434:11434
    expose:
      - 11434
    volumes:
      - ./ollama:/root/.ollama
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "ollama serve &
      sleep 10 &&
      ollama pull qwen2:0.5b &&
      wait"

  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    volumes:
      - ./qdrant_data:/qdrant/storage
    environment:
      QDRANT__LOG_LEVEL: "INFO"

  indexer:
    build: ./indexer
    volumes:
      - ${LOCAL_FILES_PATH}:/usr/src/app/local_files/
      - ./indexer:/usr/src/app
    ports:
      - 8001:8000
    environment:
      - PYTHONPATH=/usr/src
      - PYTHONUNBUFFERED=TRUE
      - LOCAL_FILES_PATH=${LOCAL_FILES_PATH}
      - EMBEDDING_MODEL_ID=${EMBEDDING_MODEL_ID}
      - EMBEDDING_SIZE=${EMBEDDING_SIZE}
      - START_INDEXING=${START_INDEXING}
    depends_on:
      - qdrant

  llm:
    build: ./llm
    volumes:
      - ./llm:/usr/src/app
    ports:
      - 8003:8000
    environment:
      - PYTHONPATH=/usr/src
      - PYTHONUNBUFFERED=TRUE
      - FIRESTORE_COLLECTION_NAME=${FIRESTORE_COLLECTION_NAME}
      - GOOGLE_APPLICATION_CREDENTIALS=${FIREBASE_KEY_FILE}
      - USER_ID=${USER_ID}
      - PASSWORD=${PASSWORD}
      - FB_PROJECT=${FB_PROJECT}
      - TASKS_COLLECTION=${TASKS_COLLECTION}
    depends_on:
      - ollama
      - qdrant
      - indexer

  nginx-reverse-proxy:
    image: nginx:latest
    ports:
      - 8080:8080
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - qdrant
      - indexer
      - ollama