openapi: 3.1.0
info:
  title: Local Computer Search API
  description: Search in local computer documents and files.
  version: 1.0.0
servers:
  - url: https://processaction-xl7gclbspq-uc.a.run.app
    description: Local Computer Search API
paths:
  /:
    get:
      operationId: answerLocalRagQuestion
      summary: Get answer to a question based on local computed documents
      parameters:
        - name: userId
          in: query
          required: true
          schema:
            type: string
          description: User identifier.
        - name: question
          in: query
          required: true
          schema:
            type: string
          description: Question that needs answer based on local computer documents.
      responses:
        '200':
          description: Answer data including status of local search and actual answer.
          content:
            application/json:
              schema:
                type: object
                properties:
                  properties:
                    type: object
                    properties:
                      status:
                        type: string
                        description: Status of the search in local computer docs.
                      answer:
                        type: string
                        description: Textual answer to the search query found in local computer docs.
                      links:
                        type: array
                        items:
                          type: string
                        description: List of text links to local files which were used to find the answer.
        '400':
          description: Invalid question or userId input.
        '500':
          description: Server error retrieving local machine search answers.
